x , y = input().split()
x = int(x)
y = int(y)
print(str(x) + " + " + str(y) + " = " + str(x + y))
print(str(x) + " * " + str(y) + " = " + str(x * y))
print(str(x) + " - " + str(y) + " = " + str(x - y))